### ISSUE TITLE
[Bug] Add check image approved keyword in vmware.log when secure boot enabled

### ISSUE THREAD

**Issue by Tomorrow9** [vmware/ansible-vsphere-gos-validation#116]
##### SUMMARY

Add a task to check image approved or not info in vmware.log in deploy_vm.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]
  jinja version = 2.11.2
  libyaml = True
```

##### CONFIGURATION

```paste below



```

##### ENVIRONMENT / OS

Deployed from ISO image

##### EXPECTED RESULTS

We can check this verification result in vmware.log when secure boot is enabled.

##### ACTUAL RESULTS

OS will not boot up when secure boot enabled and ISO image is not verified.

**Comment by keirazhang** [comment]
Fixed in https://github.com/vmware/ansible-vsphere-gos-validation/pull/266
