### ISSUE TITLE
[New Feature] Request for a common task to get default VM settings for specific guest id

### ISSUE THREAD

**Issue by keirazhang** [vmware/ansible-vsphere-gos-validation#117]
##### SUMMARY

As the subject, we need a common task to get VM default settings for a specific guest id, like default disk controller, network adapter, etc...

##### ISSUE TYPE
- Feature Idea

**Comment by Tomorrow9** [comment]
Using this module `vmware_vm_config_option`:

1. getting hardware version list with parameter set `get_hardware_versions: True` works on all vSphere versions.

2. getting guest OS IDs with parameter set `get_guest_os_ids: True`, not work when hardware version is 'vmx-17', 'vmx-18', or 'vmx-19' by default, or with parameter set to these hardware versions, e.g., `hardware_version: "vmx-17"`. Other hardware versions work.

3. getting guest recommended configs with parameter set `get_config_options: True`, `guest_id: rhel7_64Guest`, not work as above when default hardware version is 'vmx-17', 'vmx-18' or 'vmx-19', or you specify the hardware version parameter to 'vmx-17', 'vmx-18' or 'vmx-19',  e.g., `hardware_version: "vmx-17"`. Other hardware versions work.

**Comment by keirazhang** [comment]
This has been resolved in #118
