### ISSUE TITLE
[New Feature] not use delegate_to ESXi host to find keyword in vmware.log

### ISSUE THREAD

**Issue by Tomorrow9** [vmware/ansible-vsphere-gos-validation#179]
##### SUMMARY

Find other ways to search keyword in VM vmware.log instead of execute command through `delegate_to` ESXi host.
```
./common/vm_search_vmware_log.yml:35:      delegate_to: "{{ esxi_hostname }}"
./common/vm_wait_gosc_completed.yml:17:  delegate_to: "{{ esxi_hostname }}"
./windows/utils/win_empty_vmware_log.yml:12:  delegate_to: "{{ esxi_hostname }}"
./windows/utils/win_check_winbsod.yml:12:  delegate_to: "{{ esxi_hostname }}"
./windows/guest_customization/check_guest_reset_time.yml:17:      delegate_to: "{{ esxi_hostname }}"
```

##### ISSUE TYPE
- Feature Idea

##### ENVIRONMENT / OS

All

**Comment by keirazhang** [comment]
Below files have been updated/replaced by removing delegate_to in #221.
./common/vm_search_vmware_log.yml:35:      delegate_to: "{{ esxi_hostname }}"
./common/vm_wait_gosc_completed.yml:17:  delegate_to: "{{ esxi_hostname }}"
./windows/utils/win_check_winbsod.yml:12:  delegate_to: "{{ esxi_hostname }}"

Below two files haven't been changed.
./windows/utils/win_empty_vmware_log.yml:12:  delegate_to: "{{ esxi_hostname }}"
./windows/guest_customization/check_guest_reset_time.yml:17:      delegate_to: "{{ esxi_hostname }}"
