### ISSUE TITLE
[Bug] [Flatcar 3033.2.0] check_ip_address failed

### ISSUE THREAD

**Issue by Winnie81** [vmware/ansible-vsphere-gos-validation#198]
##### SUMMARY

check_ip_address case failed because IP addresses got in guest OS contains 'metric', '1024'.
Internal test run:
Ansible_Flatcar_70GA/8
Ansible_Flatcar_67GA/9

**Comment by keirazhang** [comment]
By checking one of the VM, I found the output of "ip -br addr show" doesn't like the other GOS which only output the ipv4 and ipv6 address. 
This is the output on Flatcar:
```
localhost ~ # ip -br addr show
lo               UNKNOWN        127.0.0.1/8 ::1/128 
ens192           UP             10.78.181.178/20 metric 1024 fe80::250:56ff:fea7:9a26/64 
```

This is the output on Ubuntu:
```
$ ip -br addr show
lo               UNKNOWN        127.0.0.1/8 ::1/128 
ens32            UP             10.117.16.35/23 fe80::20c:29ff:fea7:cb62/64 
docker0          DOWN           172.17.0.1/16 
br-7803a6874515  UP             172.18.0.1/16 fe80::42:70ff:fe4f:6a5d/64 
veth6a0c398@if5  UP             fe80::f412:acff:fe3f:cca/64 
```

@Winnie81 , please file a PR to Flatcar and request for a fix. I will try to workaround it in our testing code.

Thanks!

**Comment by keirazhang** [comment]
I think this issue doesn't exist in Flatcar 2983.2.1, as it passed check_ip_address.

**Comment by Winnie81** [comment]
> I think this issue doesn't exist in Flatcar 2983.2.1, as it passed check_ip_address.

Yes, I have verified it with Flatcar 2983, and will log bug to Flatcar.

**Comment by Winnie81** [comment]
https://github.com/flatcar-linux/Flatcar/issues/581 is logged.
