### ISSUE TITLE
[Bug] [Flatcar 3033.2.0]lsilogic_vhba_device_ops failed

### ISSUE THREAD

**Issue by Winnie81** [vmware/ansible-vsphere-gos-validation#199]
##### SUMMARY

Internal test run: 
Ansible_Flatcar_70GA/8
Ansible_Flatcar_67GA/10

2021-12-20 07:27:21,020 | Failed at Play [lsilogic_vhba_device_ops] ******************

2021-12-20 07:27:21,020 | TASK [Wait for device list changed] ************************
task path: /home/worker/workspace/Ansible_Flatcar_70GA/ansible-vsphere-gos-validation/linux/vhba_hot_add_remove/wait_device_list_changed.yml:97
fatal: [localhost -> 10.78.181.178]: FAILED! => {
    "attempts": 10,
    "changed": true,
    "cmd": "lsblk -o NAME,TYPE --nodeps| grep disk | awk '{print $1}'",
    "delta": "0:00:00.010402",
    "end": "2021-12-20 07:27:21.957994",
    "invocation": {
        "module_args": {
            "_raw_params": "lsblk -o NAME,TYPE --nodeps| grep disk | awk '{print $1}'",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": false
        }
    },
    "msg": "",
    "rc": 0,
    "start": "2021-12-20 07:27:21.947592",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "sda\nsdb",
    "stdout_lines": [
        "sda",
        "sdb"
    ]
}

**Comment by keirazhang** [comment]
@Winnie81 I think this is also a Flatcar issue, as after removing an LSILogicParallel disk and rescanning all SCSI devices, it still can be listed by `lsblk`. This issue doesn't appear in previous Flatcar release. Thanks!

**Comment by Winnie81** [comment]
https://github.com/flatcar-linux/Flatcar/issues/608 is logged. Thanks.
