### ISSUE TITLE
[Bug] [SLES 15 SP3] Perl GOSC is supported from VC 6.7U3

### ISSUE THREAD

**Issue by keirazhang** [vmware/ansible-vsphere-gos-validation#202]
##### SUMMARY

According to https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf, SLES 15 SP3 GOSC is supported from VC 6.7U3. Update Perl GOSC test cases to be align with it.

##### ISSUE TYPE
- Bug Report

**Comment by Tomorrow9** [comment]
Fixed with issue #205.
