### ISSUE TITLE
[Bug][Rocky Linux 8.x] Perl GOSC is supported from VC 6.7 P06 and 7.0U3

### ISSUE THREAD

**Issue by keirazhang** [vmware/ansible-vsphere-gos-validation#203]
##### SUMMARY

According to https://kb.vmware.com/s/article/86163, Rocky Linux 8.x is supported from 7.0 U3 and 6.7 P06. Update Perl GOSC test cases to be align with it.

##### ISSUE TYPE
- Bug Report

**Comment by Tomorrow9** [comment]
Fixed with https://github.com/vmware/ansible-vsphere-gos-validation/issues/205.
