### ISSUE TITLE
[Bug] [AlmaLinux 8.x] Perl GOSC is supported from 6.7 P06

### ISSUE THREAD

**Issue by keirazhang** [vmware/ansible-vsphere-gos-validation#204]
##### SUMMARY

According to https://kb.vmware.com/s/article/85686, AlmaLinux 8.x is supported from 6.7 P06. Update perl GOSC test cases to be align with it.

##### ISSUE TYPE
- Bug Report

**Comment by Tomorrow9** [comment]
Fixed with #205.
