### ISSUE TITLE
[New Feature][Linux] consider add network adpater disconnect and remove test in case network_device_ops

### ISSUE THREAD

**Issue by Tomorrow9** [vmware/ansible-vsphere-gos-validation#312]
##### SUMMARY

There lack of disconnect/disable/remove network adapter test in test case `network_device_ops`, we can consider adding these operations.

##### ISSUE TYPE
- Feature Idea

##### ENVIRONMENT / OS

Linux

**Comment by keirazhang** [comment]
Issue has been fixed in https://github.com/vmware/ansible-vsphere-gos-validation/pull/354
