### ISSUE TITLE
[New Feature] Change to use Ansible module to get ESXi host time

### ISSUE THREAD

**Issue by Tomorrow9** [vmware/ansible-vsphere-gos-validation#348]
##### SUMMARY

Change to use Ansible module to get ESXi host time in test case "stat_hosttime".

##### ISSUE TYPE
- Feature Idea

##### ENVIRONMENT / OS

Linux

**Comment by Tomorrow9** [comment]
It's better to have this module `vmware_host_facts` contain displaying the time on ESXi host, that we can use it directly. So move this to next release after module change.

**Comment by keirazhang** [comment]
@123lzxm , please help fix the linux test case stat_hosttime.yml when you add this test case for windows. Thanks
