### ISSUE TITLE
[New Feature][Ubuntu 21.04] Add to supported Guest OS list

### ISSUE THREAD

**Issue by Tomorrow9** [vmware/ansible-vsphere-gos-validation#38]
##### SUMMARY

Since Ubuntu 21.04 auto install has been added, please test on this guest OS version, and update it in the README file.

##### ISSUE TYPE
- Feature Idea

##### ENVIRONMENT / OS

Ubuntu 21.04

**Comment by ZouYuhua** [comment]
test result with ubuntu 21.04 live server GA:
![image](https://user-images.githubusercontent.com/41054978/118630177-e36cc800-b800-11eb-8219-d67e340e8e83.png)


before I did the testing for several runs with ubuntu 21.04 live-server/cloud-image/desktop daily build:
   Except two gosc testcases, all the other testcases are passed.

**Comment by keirazhang** [comment]
Resolved in https://github.com/vmware/ansible-vsphere-gos-validation/pull/40
