### ISSUE TITLE
[Bug] move check_vm_settings.yml to be executed after revert to base snasphot

### ISSUE THREAD

**Issue by Tomorrow9** [vmware/ansible-vsphere-gos-validation#397]
##### SUMMARY

`check_vm_settings.yml` is executed in `env_setup`, the VM state in this stage is not the one run testing, testing will fail if VM is not in the base snapshot (clean) state. So we can consider moving this task file after reverting VM base snapshot.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
"ansible [core 2.13.4]",
        "  config file = /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/ansible.cfg",
        "  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']",
        "  ansible python module location = /usr/lib/python3.9/site-packages/ansible",
        "  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections",
        "  executable location = /usr/bin/ansible",
        "  python version = 3.9.1 (default, Aug 19 2021, 02:58:42) [GCC 10.2.0]",
        "  jinja version = 3.0.1",
        "  libyaml = True"
```

##### CONFIGURATION

```paste below
```

##### ENVIRONMENT / OS

All

##### EXPECTED RESULTS

Testing not fail since if VM revert to the base snapshot then the checking will pass.

##### ACTUAL RESULTS

Testing failed.

**Comment by keirazhang** [comment]
Hi Yuhua,
We need to make some changes in env_setup.yml for existing VM:
1. Set default value in vars/test.yml for revert_to_snapshot to 'BaseSnapshot', and uncomment this var and 'base_snapshot_name'
2. Move condition `when: cleanup_old_snapshots | bool` into `common/vm_cleanup_snapshot.yml` for `include_tasks: vm_remove_snapshot.yml` only.
3. Move down `- include_tasks: ../common/vm_get_vm_info.yml` after `check_vm_settings.yml`.
